sudo: false

language: cpp

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang
      - perl

install:
# Install modules into ~/perl5 using system perl
  - export PATH="$PATH:~/perl5/bin"
  - export PERL5LIB=~/perl5/lib/perl5
  - export PERL_MB_OPT="--install_base '$HOME/perl5'"
  - export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
  - curl -L http://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
  - cpanm Modern::Perl Path::Tiny Test::Differences
# configure C++ version
  - if [ "$CXX" = "g++"     ]; then export CXX="g++-4.9" CC="gcc-4.9"  ; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-D__float128=void"; fi
  
script: 
  - mkdir build && cd build && cmake .. && make all && make test
